subscriptions:
  - name: Hela
    email: pengyk7@mail2.sysu.edu.cn
    topic_id: optoelectronics
    keywords:
    
  - name: Stone
    email: lixsh63@mail2.sysu.edu.cn
    topic_id: robotics
    keywords:
